export const TENURE_INSIGHTS = [
  {
    title: "What This Calculator Does",
    icon: "calculator",
    type: "list",
    items: [
      "Determines the exact loan repayment duration in months and years.",
      "Calculates tenure using EMI, loan amount, and interest rate.",
      "Shows how long your loan will take to be fully paid off.",
      "Helps identify whether your EMI is too low, ideal, or needs adjustment.",
      "Explains how interest impacts repayment time and total interest paid.",
      "Helps compare EMI options and plan faster repayment.",
    ],
  },
  {
    title: "When to Use This Calculator",
    icon: "clock",
    type: "grid",
    items: [
      "Check how long your EMI will take",
      "Decide to increase or decrease EMI",
      "Compare multiple EMI options",
      "Understand total repayment time",
      "Plan early repayments",
      "Recalculate tenure after rate changes",
      "Check remaining tenure of active loan",
      "Decide to refinance or transfer balance",
    ],
  },
  {
    title: "How to Use – Step by Step",
    icon: "steps",
    type: "steps",
    items: [
      ["Enter Annual Interest Rate", "Provide the annual loan interest rate (for example, 8.50%) offered by your bank or lender."],
      ["Enter Monthly EMI", "Enter your monthly EMI amount (for example, ₹30,000) that you plan to pay."],
      ["Enter Loan Amount", "Input the total loan amount (for example, ₹35,00,000) that you have borrowed."],
      ["View Results Instantly", "The calculator updates in real-time as you type, instantly showing the loan tenure."],
    ],
  },
  {
    title: "How This Calculator Works",
    icon: "chart",
    type: "formula",
    formula: "n = log( EMI / (EMI – P×r) ) / log(1+r)",
    meta: [
      "n = Tenure in months",
      "P = Principal loan amount",
      "r = Monthly interest rate",
      "EMI = Equated Monthly Installment",
      "Note: Solved using logarithmic transformation of the standard EMI formula.",
    ],
  },
  {
    title: "Practical Applications",
    icon: "growth",
    type: "bulb",
    items: [
      "Know your exact loan repayment duration",
      "Decide whether to increase EMI to reduce tenure",
      "Compare two EMI options for the same loan",
      "Understand long-term debt impact",
      "Check whether interest rate changes made tenure longer",
      "Test a new EMI after a salary increment",
      "Evaluate prepayment benefits",
      "Plan savings around the final loan closure",
    ],
  },
];