export const EMI_INSIGHTS = [
  {
    title: "What This Calculator Does",
    icon: "calculator",
    type: "list",
    items: [
      "Calculate the fixed monthly EMI.",
      "Understand total interest payable.",
      "Break down repayment into principal and interest.",
      "Analyze the impact of tenure and rate changes.",
      "Compare loan offers across banks.",
      "Plan monthly budgeting accurately.",
      "Assess loan affordability before applying.",
    ],
  },
  {
    title: "When to Use This Calculator",
    icon: "clock",
    type: "grid",
    items: [
      "Before applying for a home loan",
      "While planning a car purchase",
      "To compare personal loan rates",
      "To choose the right tenure",
      "Before taking a top-up loan",
      "For financial planning",
      "To avoid over-borrowing",
      "To assess EMI affordability",
    ],
  },
  {
    title: "How to Use – Step by Step",
    icon: "steps",
    type: "steps",
    items: [
      ["Enter Loan Amount (₹)", "Input the total amount you want to borrow."],
      ["Enter Interest Rate (%)", "Provide the annual interest rate."],
      ["Select Loan Tenure", "Choose repayment duration in years."],
      ["Click Calculate EMI", "Instantly see repayment details."],
      ["Review EMI Details", "Check EMI, interest, and total payment."],
    ],
  },
  {
    title: "How This Calculator Works",
    icon: "chart",
    type: "formula",
    formula: "EMI = P × r × (1+r)ⁿ / ((1+r)ⁿ − 1)",
    meta: [
      "P = Principal amount",
      "r = Monthly interest rate",
      "n = Number of months",
    ],
  },
  {
    title: "Practical Applications",
    icon: "growth",
    type: "bulb",
    items: [
      "Home & car budgeting",
      "Loan comparison",
      "Tenure optimization",
      "Prepayment planning",
      "Eligibility assessment",
      "Financial forecasting",
      "Interest impact analysis",
      "Loan restructuring",
    ],
  },
];